version: '3.9'

services:
  comfyui-docker:
    container_name: comfy-webui-docker
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/cyntachs/comfy-webui-docker:main
    ports:
      - ${PORT}:5555
    volumes:
      - ${VOLUME}:/stable-diffusion
    environment:
      - TZ="America/New_York"
      - CLI_ARGS=
    logging:
      options:
        max-size: 10m
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]