version: '3.9'

volumes:
  comfyui-docker-venv:
    name: comfyui-docker-venv

services:
  comfyui-docker:
    container_name: comfy-webui-docker
    build:
      context: .
      dockerfile: Dockerfile
    image: cyntachs/comfy-webui-docker:main
    ports:
      - ${PORT}:5555
    volumes:
      - comfyui-docker-venv:/venv
      - ${VOLUME}:/stable-diffusion
    environment:
      - TZ="America/New_York"
      - CLI_ARGS=
    logging:
      options:
        max-size: 10m
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]